@startuml

title Deployment View - SP01

node "User Personal Computer" {
    node "Java Virtual Machine" {
        component "Family Finance Management System" <<component>> {
        }
    }
}

@enduml