@startuml
left to right direction
title Class Diagram - SP02 WORK IN PROGRESS
hide empty members

package controllers {}

class Application {
}

class CategoryService {
}

class StandardCategory {
}

class CustomCategory {
}

class CategoryTreeDTO {
}

class FamilyService {
}

class FamilyMemberRelationDTO {
}

class FamilyWithoutAdministratorDTO {
}

class Family {
}

class CashAccount {
}

class FamilyMember {
}

class MemberProfileDTO {
}

class Address {
}

class CCNumber {
}

class PhoneNumber {
}

class EmailAddress {
}

class Relation {
}

class VatNumber {
}

controllers --> Application
Application --> FamilyService : has
Application --> CategoryService : has
CategoryService --> CustomCategory
CategoryService --> StandardCategory
CategoryService -left-> CategoryTreeDTO : creates
FamilyService -right-> FamilyWithoutAdministratorDTO : creates
FamilyService --> Family : has list
Family --> CashAccount : has
Family --> FamilyMember : has list
Family -right-> FamilyMemberRelationDTO : creates
FamilyMember -> CashAccount : has
FamilyMember --> Address : has
FamilyMember --> CCNumber : has
FamilyMember --> PhoneNumber : has
FamilyMember --> Relation : has
FamilyMember -left-> MemberProfileDTO : creates
FamilyMember --> EmailAddress : has
FamilyMember --> VatNumber : has
@enduml