@startuml
left to right direction

title System Overview Hypothesis III - SP02

note "System Manager has a dedicated UI and Family \nAdministrator and Members share the same UI" as a
component "Family Finance Management System" {
}
() "System Manager UI" as smUI
() "Family UI" as fUI

smUI --# "Family Finance Management System"
fUI --# "Family Finance Management System"

@enduml