@startuml

left to right direction

title Use Case Diagram - SP02

actor "Parent" as parent
actor "Family Member" as fm
actor "Family Administrator" as fa

usecase "UC106 - to change the relation between two family members" as uc106
usecase "UC111 - to add a category to the family’s category tree" as uc111
usecase "UC130 - to transfer money from the family’s cash \naccount to another family member’s cash account" as uc130
usecase "UC135 - to check the balance of the family’s \ncash account or of a given family member" as uc135
usecase "UC170 - to create a personal cash account" as uc170
usecase "UC171 - to add a bank account I have" as uc171
usecase "UC172 - to add a bank savings account I have" as uc172
usecase "UC173 - to add a credit card account I have" as uc173
usecase "UC180 - to transfer money from my cash \naccount to another family member’s cash account" as uc180
usecase "UC181 - to register a payment that I have \nmade using one of my cash accounts" as uc181
usecase "UC185 - to check the balance of one of my accounts" as uc185
usecase "UC186 - to get the list of movements \non one of my accounts between to dates" as uc186
usecase "UC188 - to check the balance of one \nof my children’s cash account" as uc188

fa -- uc106
fa -- uc111
fa -- uc130
fa -- uc135
fm -- uc170
fm -- uc171
fm -- uc172
fm -- uc173
fm -- uc180
fm -- uc181
fm -- uc185
fm -- uc186
parent -- uc188

@enduml