@startuml

autonumber

participant ": IController" as controller <<interface>>
participant ": IService" as service <<interface>>
participant "entity\n : Entity" as entity
participant ": IRepository" as repository <<interface>>
participant "savedEntity\n : Entity" as savedEntity
participant ": IRepositoryJPA" as repositoryJPA <<interface>>

-> controller : Request(requestBody)
activate controller

ref over controller
Assemble ExternalDTO to InputDTO
end

controller -> service : createEntity(inputEntityDTO)
activate service

ref over service
Assemble InputDTO to Value Objects
end

service -> entity ** : create(valueObjects)

service -> repository : add(entity)
activate repository

ref over repository
Assemble Entity to EntityJPA
end

repository -> repositoryJPA : save(entityJPA)
activate repositoryJPA
return savedEntityJPA

ref over repository
Assemble EntityJPA to Value Objects
end

repository -> savedEntity ** : create(valueObjects)

return savedEntity

ref over service
Assemble Entity to OutputDTO
end

return outputEntityDTO

ref over controller
Add Links to OutputDTO
end

return ResponseEntity\n(outputEntityDTO, HttpStatus)

@enduml